
CREATE TABLE declaracao_obito (
    id SERIAL PRIMARY KEY, -- configurar geração automatica
    -- Dados do Óbito
    TIPOBITO tipo_obito_enum NOT NULL,
    DTOBITO DATE NOT NULL,
    HORAOBITO TIME,
    IDADE VARCHAR(3) NOT NULL,
    LOCOCOR local_ocorrencia_enum NOT NULL,
    CODMUNOCOR VARCHAR(8) NOT NULL,
    CODESTAB VARCHAR(8),
    -- Dados do Falecido
    DTNASC DATE,
    SEXO sexo_enum NOT NULL,
    RACACOR raca_cor_enum,
    ESTCIV estado_civil_enum,
    ESC2010 escolaridade_nivel_2010_enum,
    SERIESCFAL SMALLINT,
    OCUP VARCHAR(6),
    CODMUNRES VARCHAR(7) NOT NULL,
    NATURAL VARCHAR(3),
    CODMUNNATU VARCHAR(7),
    -- Dados da Mãe (em caso de óbito fetal ou menor de 1 ano)
    IDADEMAE SMALLINT,
    ESCMAE2010 escolaridade_nivel_2010_enum,
    SERIESCMAE SMALLINT,
    OCUPMAE VARCHAR(6),
    QTDFILVIVO SMALLINT,
    QTDFILMORT SMALLINT,
    -- Dados da Gestação/Parto
    SEMAGESTAC SMALLINT,
    GESTACAO VARCHAR(1),
    GRAVIDEZ gravidez_tipo_enum,
    PARTO parto_tipo_enum,
    OBITOPARTO morte_parto_relacao_enum,
    PESO INTEGER,
    -- Causas da Morte
    ASSISTMED sim_nao_ignorado_enum,
    LINHAA VARCHAR(20) NOT NULL,
    LINHAB VARCHAR(20),
    LINHAC VARCHAR(20),
    LINHAD VARCHAR(20),
    LINHAII VARCHAR(45),
    CAUSABAS VARCHAR(4),
    CAUSABAS_O VARCHAR(4),
    NECROPSIA sim_nao_ignorado_enum,
    -- Atestado e Circunstâncias
    ATESTANTE atestante_condicao_enum,
    DTATESTADO DATE,
    CIRCOBITO circunstancia_obito_enum,
    ACIDTRAB sim_nao_ignorado_enum,
    FONTE fonte_informacao_enum,
    COMUNSVOIM VARCHAR(7),
    TPOBITOCOR tipo_obito_ocorrencia_acidente_enum,
    ATESTADO VARCHAR(70),
    -- Óbito de Mulher em Idade Fértil
    TPMORTEOCO tipo_morte_ocorrencia_enum,
    OBITOGRAV sim_nao_ignorado_enum,
    OBITOPUERP obito_puerperio_enum,
    CAUSAMAT VARCHAR(4),
    TPOBITOCOR_INVEST VARCHAR(1),
    -- Investigação e Controle
    EXAME sim_nao_ignorado_enum,
    CIRURGIA sim_nao_ignorado_enum,
    DTINVESTIG DATE,
    DTCADASTRO DATE,
    STCODIFICA CHAR(1),
    CODIFICADO CHAR(1),
    DTRECEBIM DATE,
    DTRECORIGA DATE,
    FONTEINV fonte_investigacao_enum,
    DTCADINV DATE,
    DTCONINV DATE,
    -- Campos Adicionais e de Sistema
    ORIGEM origem_dados_enum,
    ESC escolaridade_anos_enum,
    ESCMAE escolaridade_anos_enum,
    NUMEROLOTE VARCHAR(8),
    VERSAOSIST VARCHAR(7),
    VERSAOSCB VARCHAR(7),
    ESCMAEAGR1 escolaridade_agregada_enum,
    ESCFALAGR1 escolaridade_agregada_enum,
    STDOEPIDEM BOOLEAN,
    STDONOVA BOOLEAN,
    DIFDATA INTEGER,
    NUDIASOBCO INTEGER,
    TPRESGINFO VARCHAR(2),
    TPNIVELINV nivel_investigador_enum,
    DTCADINF DATE,
    FONTES VARCHAR(6)
);
